spring.application.name=shortener
spring.datasource.url=jdbc:postgresql://localhost:5432/shortener
spring.datasource.username=shortener
spring.datasource.password=shortener
spring.jpa.hibernate.ddl-auto=update